Wait until k6 finished

diff --git a/.github/workflows/e2e-server-test.yml b/.github/workflows/e2e-server-test.yml
--- a/.github/workflows/e2e-server-test.yml
+++ b/.github/workflows/e2e-server-test.yml
@@ -169,6 +169,22 @@ jobs:
 
       - name: Get the outputs
         run: |
+          for i in {1..20}; do
+            STATUS=$(aws ssm list-command-invocations \
+              --command-id ${{ steps.k6_test_run.outputs.command-id }} \
+              --instance-id ${{ steps.k6_test.outputs.instance_id }} \
+              --details \
+              --query "CommandInvocations[0].Status" \
+              --output text)
+            echo "Current status: $STATUS"
+            if [[ "$STATUS" == "Success" ]]; then
+              break
+            elif [[ "$STATUS" == "Failed" ]]; then
+              echo "Command failed"
+              exit 1
+            fi
+            sleep 3
+          done
           echo "The Command id is ${{ steps.k6_test_run.outputs.command-id }}"
           aws ssm get-command-invocation --command-id ${{ steps.k6_test_run.outputs.command-id }} --instance-id ${{ steps.k6_test.outputs.instance_id }}
 
